version: '2'
services:
  context-hierarchy-demo:
    ports:
      - "8080:8080"
    volumes:
      - ../target/spring-war-contexts-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    build:
      context: .
